name: twarcing
channels:
  - defaults
  - conda-forge
  - nvidia
  - anaconda
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - _r-mutex=1.0.0=anacondar_1
  - binutils_impl_linux-64=2.40=h5293946_0
  - blas=2.132=openblas
  - blas-devel=3.9.0=32_h1ea3ea9_openblas
  - bottleneck=1.4.2=py39ha9d4c09_0
  - bwidget=1.9.16=h9eba36c_0
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cairo=1.18.0=h3faef2a_0
  - cmake=3.5.0=3
  - curl=8.14.1=h332b0f4_0
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - font-ttf-inconsolata=2.001=hcb22688_0
  - font-ttf-source-code-pro=2.030=hd3eb1b0_0
  - font-ttf-ubuntu=0.83=h8b1ccd4_0
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=hd3eb1b0_0
  - freetype=2.13.3=h48d6fc4_0
  - fribidi=1.0.10=h7b6447c_0
  - gcc_impl_linux-64=11.2.0=h1234567_1
  - gfortran_impl_linux-64=11.2.0=h7a446d4_16
  - graphite2=1.3.14=h295c915_1
  - gsl=2.7.1=h6e86dc7_1
  - gxx_impl_linux-64=11.2.0=h1234567_1
  - harfbuzz=9.0.0=hfac3d4d_0
  - icu=73.2=h59595ed_0
  - kernel-headers_linux-64=5.14.0=he073ed8_2
  - krb5=1.21.3=h8a1dbc1_1
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h6a678d5_0
  - libblas=3.9.0=32_h59b9bed_openblas
  - libcblas=3.9.0=32_he106b2a_openblas
  - libcurl=8.14.1=h332b0f4_0
  - libdeflate=1.20=hd590300_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.1.0=h767d61c_3
  - libgcc-devel_linux-64=11.2.0=h1234567_1
  - libgcc-ng=15.1.0=h69a702a_3
  - libgfortran=15.1.0=h69a702a_3
  - libgfortran-ng=15.1.0=h69a702a_3
  - libgfortran5=15.1.0=hcea5267_3
  - libglib=2.82.2=h2ff4ddf_0
  - libgomp=15.1.0=h767d61c_3
  - libiconv=1.18=h4ce23a2_1
  - libjpeg-turbo=3.0.3=h5eee18b_0
  - liblapack=3.9.0=32_h7ac8fdf_openblas
  - liblapacke=3.9.0=32_he2f377e_openblas
  - libnghttp2=1.64.0=h161d5f1_0
  - libnsl=2.0.0=h5eee18b_0
  - libopenblas=0.3.30=pthreads_h94d23a6_1
  - libpng=1.6.50=h943b412_0
  - libsqlite=3.50.3=h0c1763c_1
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.1.0=h8f9b012_3
  - libstdcxx-devel_linux-64=11.2.0=h1234567_1
  - libstdcxx-ng=15.1.0=h4852527_3
  - libtiff=4.6.0=h1dd3fc0_3
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.15=h0b41bf4_0
  - libxml2=2.12.7=h4c95cb1_3
  - libzlib=1.3.1=hb9d3cd8_2
  - make=4.2.1=h1bed415_1
  - ncurses=6.4=h6a678d5_0
  - nlopt=2.9.0=py39h4c3d0a3_0
  - numexpr=2.10.1=py39hd28fd6d_0
  - numpy=1.26.4=py39heeff2f4_0
  - numpy-base=1.26.4=py39h8a23956_0
  - openblas=0.3.30=pthreads_h6ec200e_1
  - openssl=3.5.4=h26f9b46_0
  - pandoc=3.7.0.2=ha770c72_0
  - pango=1.54.0=h4c5309f_1
  - pcre2=10.44=hc749103_2
  - pip=25.1=pyhc872135_2
  - pixman=0.46.4=h537e5f6_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.9.15=hba424b6_0_cpython
  - python-dateutil=2.9.0post0=py39h06a4308_2
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.9=8_cp39
  - r-askpass=1.2.1=r44h2b5f3a1_0
  - r-base=4.4.1=h0be853a_12
  - r-base64enc=0.1_3=r44hb1dbf0f_1007
  - r-boot=1.3_31=r44hc72bb7e_0
  - r-bslib=0.9.0=r44hc72bb7e_0
  - r-cachem=1.1.0=r44hb1dbf0f_1
  - r-callr=3.7.6=r44hc72bb7e_1
  - r-cellranger=1.1.0=r44hc72bb7e_1007
  - r-cli=3.6.5=r44h93ab643_0
  - r-codetools=0.2_20=r44hc72bb7e_2
  - r-colorspace=2.1_1=r44hdb488b9_0
  - r-cpp11=0.5.2=r44h785f33e_1
  - r-crayon=1.5.3=r44hc72bb7e_1
  - r-curl=6.4.0=r44h2700575_0
  - r-digest=0.6.37=r44h0d4f4ea_0
  - r-ellipsis=0.3.2=r44hb1dbf0f_3
  - r-evaluate=1.0.4=r44hc72bb7e_0
  - r-fansi=1.0.6=r44hb1dbf0f_1
  - r-farver=2.1.2=r44ha18555a_1
  - r-fastmap=1.2.0=r44ha18555a_1
  - r-fontawesome=0.5.3=r44hc72bb7e_0
  - r-fs=1.6.6=r44h93ab643_0
  - r-future=1.67.0=r44h785f33e_1
  - r-future.apply=1.20.0=r44hc72bb7e_1
  - r-gargle=1.5.2=r44h785f33e_1
  - r-gbrd=0.4.12=r44hc72bb7e_1
  - r-ggplot2=4.0.0=r44h785f33e_0
  - r-globals=0.18.0=r44hc72bb7e_1
  - r-glue=1.8.0=r44h2b5f3a1_0
  - r-googledrive=2.1.1=r44hc72bb7e_2
  - r-googlesheets4=1.1.1=r44h785f33e_2
  - r-gtable=0.3.6=r44hc72bb7e_0
  - r-highr=0.11=r44hc72bb7e_1
  - r-htmltools=0.5.8.1=r44ha18555a_1
  - r-httr=1.4.7=r44hc72bb7e_1
  - r-ids=1.0.1=r44hc72bb7e_4
  - r-isoband=0.2.7=r44ha18555a_3
  - r-jquerylib=0.1.4=r44hc72bb7e_3
  - r-jsonlite=2.0.0=r44h2b5f3a1_0
  - r-kableextra=1.4.0=r44hc72bb7e_1
  - r-knitr=1.50=r44hc72bb7e_0
  - r-labeling=0.4.3=r44hc72bb7e_1
  - r-lattice=0.22_7=r44h2b5f3a1_0
  - r-lifecycle=1.0.4=r44hc72bb7e_1
  - r-listenv=0.9.1=r44hc72bb7e_2
  - r-lme4=1.1_37=r44h93ab643_0
  - r-lmertest=3.1_3=r44hc72bb7e_3
  - r-magrittr=2.0.3=r44hb1dbf0f_3
  - r-mass=7.3_64=r44h2b5f3a1_0
  - r-matrix=1.7_3=r44h2ae2be5_0
  - r-memoise=2.0.1=r44hc72bb7e_3
  - r-mgcv=1.9_3=r44h2ae2be5_0
  - r-mime=0.13=r44h2b5f3a1_0
  - r-minqa=1.2.8=r44ha936806_0
  - r-munsell=0.5.1=r44hc72bb7e_1
  - r-mvtnorm=1.3_3=r44h11cdb10_1
  - r-nlme=3.1_168=r44hb67ce94_0
  - r-nloptr=2.2.1=r44hb8c4c88_0
  - r-numderiv=2016.8_1.1=r44hc72bb7e_6
  - r-openssl=2.3.3=r44he8289e2_0
  - r-parallelly=1.45.1=r44h54b55ab_1
  - r-pillar=1.11.0=r44hc72bb7e_0
  - r-pkgconfig=2.0.3=r44hc72bb7e_4
  - r-processx=3.8.6=r44h2b5f3a1_0
  - r-ps=1.9.1=r44h2b5f3a1_0
  - r-purrr=1.1.0=r44h54b55ab_0
  - r-r6=2.6.1=r44hc72bb7e_0
  - r-ragg=1.3.3=r44h9aa3752_0
  - r-rappdirs=0.3.3=r44hb1dbf0f_3
  - r-rbibutils=2.3=r44h2b5f3a1_0
  - r-rcolorbrewer=1.1_3=r44h785f33e_3
  - r-rcpp=1.1.0=r44h93ab643_0
  - r-rcppeigen=0.3.4.0.2=r44hb79369c_0
  - r-rdpack=2.6.4=r44hc72bb7e_0
  - r-reformulas=0.4.1=r44hc72bb7e_0
  - r-rematch=2.0.0=r44hc72bb7e_1
  - r-rematch2=2.1.2=r44hc72bb7e_4
  - r-rlang=1.1.6=r44h93ab643_0
  - r-rmarkdown=2.29=r44hc72bb7e_0
  - r-rstudioapi=0.17.1=r44hc72bb7e_0
  - r-rvest=1.0.4=r44hc72bb7e_1
  - r-s7=0.2.0=r44h54b55ab_1
  - r-sass=0.4.10=r44h93ab643_0
  - r-scales=1.4.0=r44hc72bb7e_0
  - r-selectr=0.4_2=r44hc72bb7e_4
  - r-stringi=1.8.4=r44ha8ce623_2
  - r-stringr=1.5.1=r44h785f33e_1
  - r-svglite=2.1.3=r44h3d53355_1
  - r-sys=3.4.3=r44h2b5f3a1_0
  - r-systemfonts=1.1.0=r44h38d38ca_1
  - r-textshaping=0.4.0=r44ha47bcaa_2
  - r-tibble=3.3.0=r44h2b5f3a1_0
  - r-tinytex=0.57=r44hc72bb7e_0
  - r-utf8=1.2.6=r44h2b5f3a1_0
  - r-uuid=1.2_1=r44hdb488b9_0
  - r-vctrs=0.6.5=r44h0d4f4ea_1
  - r-viridislite=0.4.2=r44hc72bb7e_2
  - r-webshot=0.5.5=r44hc72bb7e_1
  - r-withr=3.0.2=r44hc72bb7e_0
  - r-xfun=0.52=r44h93ab643_0
  - r-xml2=1.3.6=r44h8194278_2
  - r-yaml=2.3.10=r44hdb488b9_0
  - readline=8.2=h5eee18b_0
  - sed=4.9=hb25bd0a_0
  - setuptools=78.1.1=py39h06a4308_0
  - sysroot_linux-64=2.34=h087de78_2
  - tk=8.6.13=noxft_hd72426e_102
  - tktable=2.10=h3d55465_1
  - wheel=0.45.1=py39h06a4308_0
  - xorg-kbproto=1.0.7=h5eee18b_1003
  - xorg-libice=1.1.2=h9b100fa_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.9=h8ee46fc_0
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-libxt=1.3.0=hd590300_1
  - xorg-renderproto=0.11.1=hb9d3cd8_1003
  - xorg-xextproto=7.3.0=h5eee18b_1004
  - xorg-xorgproto=2024.1=h5eee18b_0
  - xorg-xproto=7.0.31=h5eee18b_1008
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb9d3cd8_2
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
    - aiohappyeyeballs==2.3.2
    - aiohttp==3.10.0
    - aiosignal==1.3.1
    - anyio==4.4.0
    - argon2-cffi==23.1.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.3.0
    - asttokens==2.4.1
    - async-lru==2.0.4
    - async-timeout==4.0.3
    - attrs==23.2.0
    - babel==2.15.0
    - beautifulsoup4==4.12.3
    - bleach==6.1.0
    - certifi==2024.7.4
    - cffi==1.16.0
    - charset-normalizer==3.3.2
    - click==8.1.7
    - click-config-file==0.6.0
    - click-plugins==1.1.1
    - comm==0.2.2
    - configobj==5.0.8
    - contourpy==1.2.1
    - coverage==6.5.0
    - cycler==0.12.1
    - debugpy==1.8.2
    - decorator==5.1.1
    - defusedxml==0.7.1
    - et-xmlfile==1.1.0
    - exceptiongroup==1.2.2
    - executing==2.0.1
    - factor-analyzer==0.5.1
    - fastjsonschema==2.20.0
    - fonttools==4.53.1
    - fqdn==1.5.1
    - frozenlist==1.4.1
    - h11==0.14.0
    - httpcore==1.0.5
    - httpx==0.27.0
    - huggingface-hub==0.17.3
    - humanize==4.10.0
    - idna==3.7
    - importlib-metadata==8.2.0
    - importlib-resources==6.4.0
    - ipykernel==6.29.5
    - ipython==8.18.1
    - ipywidgets==8.1.3
    - irrcac==0.4.1
    - isoduration==20.11.0
    - jedi==0.19.1
    - joblib==1.4.2
    - json5==0.9.25
    - jsonpointer==3.0.0
    - jsonschema==4.23.0
    - jsonschema-specifications==2023.12.1
    - jupyter==1.0.0
    - jupyter-client==8.6.2
    - jupyter-console==6.6.3
    - jupyter-core==5.7.2
    - jupyter-events==0.10.0
    - jupyter-lsp==2.2.5
    - jupyter-server==2.14.2
    - jupyter-server-terminals==0.5.3
    - jupyterlab==4.2.4
    - jupyterlab-pygments==0.3.0
    - jupyterlab-server==2.27.3
    - jupyterlab-widgets==3.0.11
    - kiwisolver==1.4.5
    - marginaleffects==0.0.12
    - matplotlib==3.9.1
    - matplotlib-inline==0.1.7
    - mistune==3.0.2
    - mizani==0.11.4
    - more-itertools==10.3.0
    - multidict==6.0.4
    - nbclient==0.10.0
    - nbconvert==7.16.4
    - nbformat==5.10.4
    - nest-asyncio==1.6.0
    - nltk==3.9.1
    - notebook==7.2.1
    - notebook-shim==0.2.4
    - oauthlib==3.2.2
    - openpyxl==3.1.4
    - overrides==7.7.0
    - pandas==2.3.2
    - pandocfilters==1.5.1
    - parso==0.8.4
    - patsy==0.5.6
    - pexpect==4.9.0
    - pillow==10.4.0
    - platformdirs==4.2.2
    - plotnine==0.13.6
    - polars==1.33.1
    - powerlaw==1.5
    - prometheus-client==0.20.0
    - prompt-toolkit==3.0.47
    - psutil==6.0.0
    - ptyprocess==0.7.0
    - pure-eval==0.2.3
    - pyarrow==14.0.2
    - pycparser==2.22
    - pygments==2.18.0
    - pyparsing==3.1.2
    - python-json-logger==2.0.7
    - pytorch-lightning==2.1.1
    - pytz==2024.1
    - pyzmq==26.0.3
    - qtconsole==5.5.2
    - qtpy==2.4.1
    - referencing==0.35.1
    - requests==2.32.3
    - requests-oauthlib==1.3.1
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rpds-py==0.19.1
    - scikit-learn==1.3.0
    - scipy==1.11.2
    - seaborn==0.12.2
    - send2trash==1.8.3
    - shifterator==0.3.0
    - six==1.16.0
    - sniffio==1.3.1
    - soupsieve==2.5
    - stack-data==0.6.3
    - statsmodels==0.14.4
    - terminado==0.18.1
    - threadpoolctl==3.5.0
    - tinycss2==1.3.0
    - tokenizers==0.14.1
    - tomli==2.0.1
    - torch==2.1.0
    - tornado==6.4.1
    - tqdm==4.65.0
    - traitlets==5.14.3
    - transformers==4.35.1
    - twarc==2.14.0
    - twarc-csv==0.7.1
    - types-python-dateutil==2.9.0.20240316
    - tzdata==2024.1
    - uri-template==1.3.0
    - urllib3==1.26.19
    - wcwidth==0.2.13
    - webcolors==24.6.0
    - webencodings==0.5.1
    - websocket-client==1.8.0
    - widgetsnbextension==4.0.11
    - xargs==0.5.0
    - yarl==1.9.4
    - zipp==3.19.2
prefix: /home/luehring/.conda/envs/twarcing
